{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-core",
    "version": "2.19.1-labi.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.8.aar",
          "url": "exoplayer-core-2.19.1-labi.8.aar",
          "size": 1281787,
          "sha512": "67c74da64a997f0ca2d9739afed5ef2be31c5d9470230e1595a813b55a56f00c720e3eb10c117e0add978acb4780ac1b1f609d983d124cd8ad906d9f2d474cb6",
          "sha256": "d3729a1bd9d2f24fb272f6a053b8b7ead2a117f80774a03a10f27cee90460f3e",
          "sha1": "a17fd2ba080b78e074a16798aabce98d16737069",
          "md5": "f5eb49661c8d7edaf08defc07d162256"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.8.aar",
          "url": "exoplayer-core-2.19.1-labi.8.aar",
          "size": 1281787,
          "sha512": "67c74da64a997f0ca2d9739afed5ef2be31c5d9470230e1595a813b55a56f00c720e3eb10c117e0add978acb4780ac1b1f609d983d124cd8ad906d9f2d474cb6",
          "sha256": "d3729a1bd9d2f24fb272f6a053b8b7ead2a117f80774a03a10f27cee90460f3e",
          "sha1": "a17fd2ba080b78e074a16798aabce98d16737069",
          "md5": "f5eb49661c8d7edaf08defc07d162256"
        }
      ]
    }
  ]
}
