{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.13.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.13.aar",
          "size": 224574,
          "sha512": "f644c8dae630b8a3e82d1611854f991768e3896f93aa98cff16c5e9c0010364462f0210a6e3f4fdc7de5ff2e2a9d9b07a186a2c961f6f291277ed3e4b724193c",
          "sha256": "f85bc6ec28e6adee4e9ff99d20b407ad4514d6635fd1f29b3b0e060dd55cfd27",
          "sha1": "7ad0b40bda5106bf748dc1decfb39f47be98aff9",
          "md5": "4e70b90a948be33e8c8e0802628cbcbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.13"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.13.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.13.aar",
          "size": 224574,
          "sha512": "f644c8dae630b8a3e82d1611854f991768e3896f93aa98cff16c5e9c0010364462f0210a6e3f4fdc7de5ff2e2a9d9b07a186a2c961f6f291277ed3e4b724193c",
          "sha256": "f85bc6ec28e6adee4e9ff99d20b407ad4514d6635fd1f29b3b0e060dd55cfd27",
          "sha1": "7ad0b40bda5106bf748dc1decfb39f47be98aff9",
          "md5": "4e70b90a948be33e8c8e0802628cbcbb"
        }
      ]
    }
  ]
}
