{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-core",
    "version": "2.19.1-labi.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.31.aar",
          "url": "exoplayer-core-2.19.1-labi.31.aar",
          "size": 1292102,
          "sha512": "6b94c4875c955186ac2e986c7d9bac290ce0f7c95d7b893e70a43dfeeb97b62a6b4cce978bea216476e1339dd1794fe2e038ef7dc2d40e0889f7972df3b4d454",
          "sha256": "b3c4ec2241a8ced41d85a058df86fcf7c69954ff68f1a3589c6d8fb980a48dc5",
          "sha1": "1033a5b89cb97ce3167dec28661233c5a95ce6fb",
          "md5": "bfa83833f27c31e589b9b491128689ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.31"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.31.aar",
          "url": "exoplayer-core-2.19.1-labi.31.aar",
          "size": 1292102,
          "sha512": "6b94c4875c955186ac2e986c7d9bac290ce0f7c95d7b893e70a43dfeeb97b62a6b4cce978bea216476e1339dd1794fe2e038ef7dc2d40e0889f7972df3b4d454",
          "sha256": "b3c4ec2241a8ced41d85a058df86fcf7c69954ff68f1a3589c6d8fb980a48dc5",
          "sha1": "1033a5b89cb97ce3167dec28661233c5a95ce6fb",
          "md5": "bfa83833f27c31e589b9b491128689ae"
        }
      ]
    }
  ]
}
