{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-core",
    "version": "2.19.1-labi.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.30.aar",
          "url": "exoplayer-core-2.19.1-labi.30.aar",
          "size": 1292089,
          "sha512": "9506ff3c22c16c9fe0c976138ac528f812ad54304f6b6583d92f509766c20e7c2aadb4a00e8ef23eb1fdb04ae2c1f9620988b0edea2a996cf4f7ca2190672247",
          "sha256": "83207e7250f8156c6da49cfe6b57587adff5e7107a3d5349d1872f94af3c2c71",
          "sha1": "9876a01760258a12d7e5b0ffa79b3910ae51480d",
          "md5": "9a52637cb9bb13d5a41d9d545eabd9d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.30.aar",
          "url": "exoplayer-core-2.19.1-labi.30.aar",
          "size": 1292089,
          "sha512": "9506ff3c22c16c9fe0c976138ac528f812ad54304f6b6583d92f509766c20e7c2aadb4a00e8ef23eb1fdb04ae2c1f9620988b0edea2a996cf4f7ca2190672247",
          "sha256": "83207e7250f8156c6da49cfe6b57587adff5e7107a3d5349d1872f94af3c2c71",
          "sha1": "9876a01760258a12d7e5b0ffa79b3910ae51480d",
          "md5": "9a52637cb9bb13d5a41d9d545eabd9d5"
        }
      ]
    }
  ]
}
