{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.11.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.11.aar",
          "size": 216902,
          "sha512": "a3af2a003cb1f77f380b4858c0e1ac3c85cb5eb8475d3ed96fb7e9ea5315281c613e86d7313df9edcdce780a678cad0f105161c2435fe34ded6480f577d385e8",
          "sha256": "33fd61dbca15833f01f45bb9badec28147654aea339128c265dd3367c5387723",
          "sha1": "0d69360e31d822da30984bcafcbb51f2e5b93bd4",
          "md5": "741dc0b30d06e511b35dcf8df1e32820"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.11"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.11.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.11.aar",
          "size": 216902,
          "sha512": "a3af2a003cb1f77f380b4858c0e1ac3c85cb5eb8475d3ed96fb7e9ea5315281c613e86d7313df9edcdce780a678cad0f105161c2435fe34ded6480f577d385e8",
          "sha256": "33fd61dbca15833f01f45bb9badec28147654aea339128c265dd3367c5387723",
          "sha1": "0d69360e31d822da30984bcafcbb51f2e5b93bd4",
          "md5": "741dc0b30d06e511b35dcf8df1e32820"
        }
      ]
    }
  ]
}
