{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.24.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.24.aar",
          "size": 236877,
          "sha512": "14b2c8c20255c07dcc271c78a21db747949bc1425b62fa31581f5ceabdaade95fca08aab14a40ef38d7070d051375614dd6c257de2b2c1e23b77565053960cb5",
          "sha256": "1c2977c5b6df0cfa63a45b48c89c922576711672ffa9e13a52085738c6abeabe",
          "sha1": "172e70d5d7b15ebed3eb1952d225eceb129aa5e1",
          "md5": "f3d4a1ac3cb429b9010f9ed8e1c57f34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.24"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.24.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.24.aar",
          "size": 236877,
          "sha512": "14b2c8c20255c07dcc271c78a21db747949bc1425b62fa31581f5ceabdaade95fca08aab14a40ef38d7070d051375614dd6c257de2b2c1e23b77565053960cb5",
          "sha256": "1c2977c5b6df0cfa63a45b48c89c922576711672ffa9e13a52085738c6abeabe",
          "sha1": "172e70d5d7b15ebed3eb1952d225eceb129aa5e1",
          "md5": "f3d4a1ac3cb429b9010f9ed8e1c57f34"
        }
      ]
    }
  ]
}
