{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.1.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.1.aar",
          "size": 175947,
          "sha512": "e5bf5f29bd9cb445d02906227e4bc6d07db8fbfd685a63bca0a327cedd9a618c607fb2b577ff317b2aeb6bc0ebf57cd0c8e87e9d56c6de1677bf0b7c2c750f58",
          "sha256": "3e6745b0dfd1f7a3a4b607f966977669bb92c1b8bc94153f612f2ca17880ce1a",
          "sha1": "ac54a9ad1fcb3eaa1ad7c1a85d08a6951259c75b",
          "md5": "44bde9f7ee79f2737218674132a7fc1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.1"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.1.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.1.aar",
          "size": 175947,
          "sha512": "e5bf5f29bd9cb445d02906227e4bc6d07db8fbfd685a63bca0a327cedd9a618c607fb2b577ff317b2aeb6bc0ebf57cd0c8e87e9d56c6de1677bf0b7c2c750f58",
          "sha256": "3e6745b0dfd1f7a3a4b607f966977669bb92c1b8bc94153f612f2ca17880ce1a",
          "sha1": "ac54a9ad1fcb3eaa1ad7c1a85d08a6951259c75b",
          "md5": "44bde9f7ee79f2737218674132a7fc1b"
        }
      ]
    }
  ]
}
