{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.3.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.3.aar",
          "size": 179311,
          "sha512": "c47cc5a933a1fb7224907e7dfb7b97159007813a460fdfc7689b7e3403d47fa1409e29e16eed60e99e319f941fda9fd2af59739a48738ac5791052ef0b2b8be0",
          "sha256": "43ded99b35d2cc06d447c91f217b3ca24b1062a285cd8da592789902b4463e0c",
          "sha1": "52a3bebe48fa2df3805d95f3e28578b3234c8c59",
          "md5": "a48e7a71e3be53fdd48339170d1e86d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.3"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.3.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.3.aar",
          "size": 179311,
          "sha512": "c47cc5a933a1fb7224907e7dfb7b97159007813a460fdfc7689b7e3403d47fa1409e29e16eed60e99e319f941fda9fd2af59739a48738ac5791052ef0b2b8be0",
          "sha256": "43ded99b35d2cc06d447c91f217b3ca24b1062a285cd8da592789902b4463e0c",
          "sha1": "52a3bebe48fa2df3805d95f3e28578b3234c8c59",
          "md5": "a48e7a71e3be53fdd48339170d1e86d8"
        }
      ]
    }
  ]
}
