{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.8.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.8.aar",
          "size": 201008,
          "sha512": "e434840c120e33a74add868f7c78481b4c0ad092a91c6ef7d37da2aa5a5c05d6ac0cec8801356d3f10e7cc192aa44cd3410bb5a730aecc1c12adf6e71c835061",
          "sha256": "1baab928361874d106530059d65362a3df38b07ce9b3dcba1eb2c987d14f3102",
          "sha1": "ddac7fed46dee11a7fa4f6a038330f500035bf96",
          "md5": "075891b34ba3815dfac1e7d20f259021"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.8"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.8.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.8.aar",
          "size": 201008,
          "sha512": "e434840c120e33a74add868f7c78481b4c0ad092a91c6ef7d37da2aa5a5c05d6ac0cec8801356d3f10e7cc192aa44cd3410bb5a730aecc1c12adf6e71c835061",
          "sha256": "1baab928361874d106530059d65362a3df38b07ce9b3dcba1eb2c987d14f3102",
          "sha1": "ddac7fed46dee11a7fa4f6a038330f500035bf96",
          "md5": "075891b34ba3815dfac1e7d20f259021"
        }
      ]
    }
  ]
}
