{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.4.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.4.aar",
          "size": 183020,
          "sha512": "2cc92aa32b901408a06417c968bba662f3c39ec0b9d803b6893548b53a89ca54782a5c000fef0c318c5be2191d2c162044f464a576e37e7bf648591df1f9657c",
          "sha256": "9668b29cf70c14307133e4a4f58c48f4640b48531c334c47310ba69b5fb107e4",
          "sha1": "2fb9d15748b71265d793c28feeac09d8099c85dd",
          "md5": "f7b3da06d50b4a9ba635c4bbbb3952e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.4.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.4.aar",
          "size": 183020,
          "sha512": "2cc92aa32b901408a06417c968bba662f3c39ec0b9d803b6893548b53a89ca54782a5c000fef0c318c5be2191d2c162044f464a576e37e7bf648591df1f9657c",
          "sha256": "9668b29cf70c14307133e4a4f58c48f4640b48531c334c47310ba69b5fb107e4",
          "sha1": "2fb9d15748b71265d793c28feeac09d8099c85dd",
          "md5": "f7b3da06d50b4a9ba635c4bbbb3952e1"
        }
      ]
    }
  ]
}
