{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.30.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.30.aar",
          "size": 241150,
          "sha512": "6eea992db6f6f43a98dde438fe68b707d55cb49c1cc64f152c6c997cacbcf843ec536d3d5bd8eee0b5ec85636b1d1dd255ac00e1034a1f60ac7c80f5b756253e",
          "sha256": "cbd22f1e184c1a72a9d228dd3a5742fd98b6e218623b76797338955835bfc9a4",
          "sha1": "e5ed258efd044d048b831285b3cafa3543c2ab10",
          "md5": "29b2b2ab4771d0f1ba706d0dd21106fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.30"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.30.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.30.aar",
          "size": 241150,
          "sha512": "6eea992db6f6f43a98dde438fe68b707d55cb49c1cc64f152c6c997cacbcf843ec536d3d5bd8eee0b5ec85636b1d1dd255ac00e1034a1f60ac7c80f5b756253e",
          "sha256": "cbd22f1e184c1a72a9d228dd3a5742fd98b6e218623b76797338955835bfc9a4",
          "sha1": "e5ed258efd044d048b831285b3cafa3543c2ab10",
          "md5": "29b2b2ab4771d0f1ba706d0dd21106fe"
        }
      ]
    }
  ]
}
