{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.2.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.2.aar",
          "size": 179192,
          "sha512": "e906ec8c5500e8c4cb1d57a33e94d7e0e2b92b12210dd87e5c4a209820955be07489042d91d296543ac2317038c73805319c48f6bad1161def3b99726756bd95",
          "sha256": "70709b176b0ca811924467aec9674843a284ae89fb07740c4dcdd21191049827",
          "sha1": "33627136fc87a3f9dfe1256166b803c6c074ea13",
          "md5": "703b147022b59643927d47efcc9cb053"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.2"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.2.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.2.aar",
          "size": 179192,
          "sha512": "e906ec8c5500e8c4cb1d57a33e94d7e0e2b92b12210dd87e5c4a209820955be07489042d91d296543ac2317038c73805319c48f6bad1161def3b99726756bd95",
          "sha256": "70709b176b0ca811924467aec9674843a284ae89fb07740c4dcdd21191049827",
          "sha1": "33627136fc87a3f9dfe1256166b803c6c074ea13",
          "md5": "703b147022b59643927d47efcc9cb053"
        }
      ]
    }
  ]
}
