{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.19.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.19.aar",
          "size": 231387,
          "sha512": "9ce6557b76b28cc2f0023345b86ddf9ba72545593f6c3d02aed6da41121d51ca390b744229a78be2eda23e8a88e5b37e03216cf53d91c9a0038a16191170bcdd",
          "sha256": "00f2fcdbf107980e5c32d5fe4c7f707359358f2b0d7ecacd6f34bf4f0170d219",
          "sha1": "a94d08791d41fa5d4abe39b65af9f119b6a0eb23",
          "md5": "48fb9f43b70db5a8b90a812d511f8392"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.19"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.19.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.19.aar",
          "size": 231387,
          "sha512": "9ce6557b76b28cc2f0023345b86ddf9ba72545593f6c3d02aed6da41121d51ca390b744229a78be2eda23e8a88e5b37e03216cf53d91c9a0038a16191170bcdd",
          "sha256": "00f2fcdbf107980e5c32d5fe4c7f707359358f2b0d7ecacd6f34bf4f0170d219",
          "sha1": "a94d08791d41fa5d4abe39b65af9f119b6a0eb23",
          "md5": "48fb9f43b70db5a8b90a812d511f8392"
        }
      ]
    }
  ]
}
