{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-core",
    "version": "2.19.1-labi.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.28.aar",
          "url": "exoplayer-core-2.19.1-labi.28.aar",
          "size": 1289990,
          "sha512": "b259e1b9d9b4b4a0cb27217d2a9bd7f19385020bb0f65e3d502d717b3113b24bb34a9632c52be43df8ebbf8554d2f6252e4ea982442c6584bc3b61c2cf74b31a",
          "sha256": "132feeec3d8996f2ab6fb2fc01ff13b5822546663e05f24ef4eefa9e8704875b",
          "sha1": "beba6b6d92a63c18c0dc3fe520754f2faed195f9",
          "md5": "26b6be5d1c13bec0b9843f5c2c3e574c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.28.aar",
          "url": "exoplayer-core-2.19.1-labi.28.aar",
          "size": 1289990,
          "sha512": "b259e1b9d9b4b4a0cb27217d2a9bd7f19385020bb0f65e3d502d717b3113b24bb34a9632c52be43df8ebbf8554d2f6252e4ea982442c6584bc3b61c2cf74b31a",
          "sha256": "132feeec3d8996f2ab6fb2fc01ff13b5822546663e05f24ef4eefa9e8704875b",
          "sha1": "beba6b6d92a63c18c0dc3fe520754f2faed195f9",
          "md5": "26b6be5d1c13bec0b9843f5c2c3e574c"
        }
      ]
    }
  ]
}
