{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.23.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.23.aar",
          "size": 236670,
          "sha512": "46c6800c32b7f3e7ca6da49dc606582abf87f042b85d6c81b0bba4913fdaae2f18d43ec4ba78bd703263974adbd13ccbb5834694746bdc7cd9b5076b025a9c5b",
          "sha256": "3ebae7acd4e60ca10299594a619db07de9db0ac8f5e261935c594f94fa0d05cd",
          "sha1": "03afa92adad3d42253cc9613f65892bf29eded9c",
          "md5": "1a1773b50252615a2710419f9cf57fcb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.23"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.23.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.23.aar",
          "size": 236670,
          "sha512": "46c6800c32b7f3e7ca6da49dc606582abf87f042b85d6c81b0bba4913fdaae2f18d43ec4ba78bd703263974adbd13ccbb5834694746bdc7cd9b5076b025a9c5b",
          "sha256": "3ebae7acd4e60ca10299594a619db07de9db0ac8f5e261935c594f94fa0d05cd",
          "sha1": "03afa92adad3d42253cc9613f65892bf29eded9c",
          "md5": "1a1773b50252615a2710419f9cf57fcb"
        }
      ]
    }
  ]
}
