{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.28.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.28.aar",
          "size": 239521,
          "sha512": "2753658688beb710ca46e1635d827a3a434ebfcfbe36e8f11e70a75c6b905d8d839f53391f9f27d73365becece8eb0d30afba24d4e118e8b69d9331e99a292da",
          "sha256": "042af27d851de87fccc3c882a59f9b343045e2ad2f49f33e4150e49b4198a521",
          "sha1": "1f11c12b1d6bdefc3786a95cf5d624029296e8bc",
          "md5": "cefc85f0da710ecf9e64076af93ef00a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.28"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.28.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.28.aar",
          "size": 239521,
          "sha512": "2753658688beb710ca46e1635d827a3a434ebfcfbe36e8f11e70a75c6b905d8d839f53391f9f27d73365becece8eb0d30afba24d4e118e8b69d9331e99a292da",
          "sha256": "042af27d851de87fccc3c882a59f9b343045e2ad2f49f33e4150e49b4198a521",
          "sha1": "1f11c12b1d6bdefc3786a95cf5d624029296e8bc",
          "md5": "cefc85f0da710ecf9e64076af93ef00a"
        }
      ]
    }
  ]
}
