{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.14.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.14.aar",
          "size": 228088,
          "sha512": "6e78845c026d1e233f231e39bf9a66a1f03b959432383dd1e3065b59823d4e755917c37b5ff6d663341889085a9efcd6580c69d1e67116484319306f098aa80a",
          "sha256": "b7d93208e8d0621abc77b0305ceddf3937252011807f1e886a7737ff9400b090",
          "sha1": "ff8ded927e71919a28271fd2251febf18d8f6a30",
          "md5": "500d5634d6261f34712f5b4b49f42030"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.14"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.14.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.14.aar",
          "size": 228088,
          "sha512": "6e78845c026d1e233f231e39bf9a66a1f03b959432383dd1e3065b59823d4e755917c37b5ff6d663341889085a9efcd6580c69d1e67116484319306f098aa80a",
          "sha256": "b7d93208e8d0621abc77b0305ceddf3937252011807f1e886a7737ff9400b090",
          "sha1": "ff8ded927e71919a28271fd2251febf18d8f6a30",
          "md5": "500d5634d6261f34712f5b4b49f42030"
        }
      ]
    }
  ]
}
