{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-core",
    "version": "2.19.1-labi.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.32.aar",
          "url": "exoplayer-core-2.19.1-labi.32.aar",
          "size": 1292268,
          "sha512": "d259e156d536c57db33247c54a34c3de9882a16d0f9e3291293a91c6295c59665cdf2f48c96616849379e66a63ba462daca70508b5dae71b6d391fbcd4f4b4bd",
          "sha256": "07902daafb2d75c40cd9ac1b2700b3549b884300f72cc84f285fefa6c3b87331",
          "sha1": "da34a88f1add82982836c49f02c1cbc19de3be50",
          "md5": "66194f3a1651a207d00385f5a5d92abc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.32"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.32.aar",
          "url": "exoplayer-core-2.19.1-labi.32.aar",
          "size": 1292268,
          "sha512": "d259e156d536c57db33247c54a34c3de9882a16d0f9e3291293a91c6295c59665cdf2f48c96616849379e66a63ba462daca70508b5dae71b6d391fbcd4f4b4bd",
          "sha256": "07902daafb2d75c40cd9ac1b2700b3549b884300f72cc84f285fefa6c3b87331",
          "sha1": "da34a88f1add82982836c49f02c1cbc19de3be50",
          "md5": "66194f3a1651a207d00385f5a5d92abc"
        }
      ]
    }
  ]
}
