{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.22.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.22.aar",
          "size": 236161,
          "sha512": "e67c209724bf82d3f2c88ba8f51052a29e609568bfbbb244c6222c74f9d8edddf527f49577ab9d1c9aaa7bc3f5b1f629638d5c4b807ea2944c4af956f38b74e9",
          "sha256": "48f91497d1b26b6b152ba37c1f363765f50963cfd5e2cab5bcc5eafc08023e86",
          "sha1": "a689acf071c70481eafbf0fb95f635a31835314c",
          "md5": "e2d4b8dc4892f098c9ce322a1ceb39be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.22"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.22.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.22.aar",
          "size": 236161,
          "sha512": "e67c209724bf82d3f2c88ba8f51052a29e609568bfbbb244c6222c74f9d8edddf527f49577ab9d1c9aaa7bc3f5b1f629638d5c4b807ea2944c4af956f38b74e9",
          "sha256": "48f91497d1b26b6b152ba37c1f363765f50963cfd5e2cab5bcc5eafc08023e86",
          "sha1": "a689acf071c70481eafbf0fb95f635a31835314c",
          "md5": "e2d4b8dc4892f098c9ce322a1ceb39be"
        }
      ]
    }
  ]
}
