{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.33.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.33.aar",
          "size": 241329,
          "sha512": "38ad05e63e1e37ec2a527cab0f66393b8cf8fcefa03315782233f7b91afbf223f629be08b0a047c2c6e00a6184d1eda0e4b49ce3445474a05d7297a20bbf1e1b",
          "sha256": "6d902329dbdb033407fc574c138a5f821685e4569cc60ea5c62816444dc789c3",
          "sha1": "b66e26ee98e8799171f2527ceca07f3755507a6f",
          "md5": "0e2514c46776cf966cee10fe955c87a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.33"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.33.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.33.aar",
          "size": 241329,
          "sha512": "38ad05e63e1e37ec2a527cab0f66393b8cf8fcefa03315782233f7b91afbf223f629be08b0a047c2c6e00a6184d1eda0e4b49ce3445474a05d7297a20bbf1e1b",
          "sha256": "6d902329dbdb033407fc574c138a5f821685e4569cc60ea5c62816444dc789c3",
          "sha1": "b66e26ee98e8799171f2527ceca07f3755507a6f",
          "md5": "0e2514c46776cf966cee10fe955c87a0"
        }
      ]
    }
  ]
}
