{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-core",
    "version": "2.19.1-labi.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.4.aar",
          "url": "exoplayer-core-2.19.1-labi.4.aar",
          "size": 1281467,
          "sha512": "797d7f78efc4a471286b8f3893f96eeb92c5e3156965e3d2157b344aceb81a0664ed5387752852faad544e76303530a54b5e6338e6b3a80da712939f289097e3",
          "sha256": "e89b76f0d496d10cef1b5ee0d7606052875fd23a56ae64a8083b3a614f2a530d",
          "sha1": "00cd567e1da367fe15cb10001306f40a4f7322e1",
          "md5": "4336e5eeca61108fa295c6a314b92d2e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-container",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.19.1-labi.4"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.19.1-labi.4.aar",
          "url": "exoplayer-core-2.19.1-labi.4.aar",
          "size": 1281467,
          "sha512": "797d7f78efc4a471286b8f3893f96eeb92c5e3156965e3d2157b344aceb81a0664ed5387752852faad544e76303530a54b5e6338e6b3a80da712939f289097e3",
          "sha256": "e89b76f0d496d10cef1b5ee0d7606052875fd23a56ae64a8083b3a614f2a530d",
          "sha1": "00cd567e1da367fe15cb10001306f40a4f7322e1",
          "md5": "4336e5eeca61108fa295c6a314b92d2e"
        }
      ]
    }
  ]
}
