{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zknowai.exoplayer",
    "module": "exoplayer-rtsp",
    "version": "2.19.1-labi.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.12.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.12.aar",
          "size": 224541,
          "sha512": "0acd3c94b2f5c8c40c2e33554d2b1108743f9327926dcaea53ddd236c4db5a4a27547dc6148b1597f9ef79d743aca4b162e5efe6e5b354b90d693875a2e5f871",
          "sha256": "e0914be6b3b06b2eaf48532c58b765321b5c88c15cbf497145356581724cc14f",
          "sha1": "118bc45d2eacdb86428dc7223d6eac4338bd0267",
          "md5": "d0df64ad2a7fddde27d63926a3d76945"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.zknowai.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1-labi.12"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-rtsp-2.19.1-labi.12.aar",
          "url": "exoplayer-rtsp-2.19.1-labi.12.aar",
          "size": 224541,
          "sha512": "0acd3c94b2f5c8c40c2e33554d2b1108743f9327926dcaea53ddd236c4db5a4a27547dc6148b1597f9ef79d743aca4b162e5efe6e5b354b90d693875a2e5f871",
          "sha256": "e0914be6b3b06b2eaf48532c58b765321b5c88c15cbf497145356581724cc14f",
          "sha1": "118bc45d2eacdb86428dc7223d6eac4338bd0267",
          "md5": "d0df64ad2a7fddde27d63926a3d76945"
        }
      ]
    }
  ]
}
